<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/10/20 00:39:52
sfConfig::add(array(
  'app_upload_limit' => -1.0,
  'app_download_timeout' => 10,
  'app_cache_engine' => 'sfMemcacheCache',
  'app_read_only' => false,
  'app_google_analytics_api_key' => NULL,
  'app_google_analytics_institutions_dimension_index' => NULL,
  'app_google_tag_manager_container_id' => NULL,
  'app_htmlpurifier_enabled' => false,
  'app_workers_key' => NULL,
  'app_password_hash_algorithm' => 'PASSWORD_ARGON2I',
  'app_password_hash_algorithm_options_memory_cost' => '2048',
  'app_password_hash_algorithm_options_time_cost' => '4',
  'app_password_hash_algorithm_options_threads' => '3',
  'app_treeview_items_per_page_max' => 10000,
  'app_cache_engine_param_storeCacheInfo' => 'yes',
  'app_cache_engine_param_prefix' => 'atom',
  'app_cache_engine_param_host' => '127.0.0.1',
  'app_cache_engine_param_port' => 11211,
  'app_cache_engine_param_persistent' => 'yes',
));
