<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/10/19 17:39:53
sfConfig::add(array(
  'mod_sfpluginadminplugin_enabled' => true,
  'mod_sfpluginadminplugin_view_class' => 'sfPHP',
));
