<?php
// auto-generated by sfSecurityConfigHandler
// date: 2024/10/19 17:39:53
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'autocomplete' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'administrator',
        1 => 'contributor',
        2 => 'editor',
      ),
    ),
  ),
  'boxlist' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'administrator',
        1 => 'editor',
      ),
    ),
  ),
  'browse' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'administrator',
        1 => 'editor',
        2 => 'translator',
      ),
    ),
  ),
  'delete' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'administrator',
        1 => 'editor',
      ),
    ),
  ),
  'edit' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'administrator',
        1 => 'editor',
        2 => 'translator',
      ),
    ),
  ),
  'index' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'administrator',
        1 => 'contributor',
        2 => 'editor',
        3 => 'translator',
      ),
    ),
  ),
);
