<?php
// auto-generated by sfCacheConfigHandler
// date: 2024/10/19 17:39:53
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

