<?php
// auto-generated by sfSecurityConfigHandler
// date: 2024/10/19 17:39:53
$this->security = array (
  'browse' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'editor',
        1 => 'administrator',
      ),
    ),
  ),
  'list' => 
  array (
    'credentials' => 
    array (
      0 => 
      array (
        0 => 'editor',
        1 => 'administrator',
      ),
    ),
  ),
  'index' => 
  array (
    'is_secure' => false,
  ),
  'autocomplete' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
