<?php
// auto-generated by sfSecurityConfigHandler
// date: 2024/10/19 17:39:53
$this->security = array (
  'delete' => 
  array (
    'credentials' => 'administrator',
    'is_secure' => true,
  ),
  'edit' => 
  array (
    'credentials' => 'administrator',
    'is_secure' => true,
  ),
  'list' => 
  array (
    'credentials' => 'administrator',
    'is_secure' => true,
  ),
  'all' => 
  array (
    'is_secure' => false,
  ),
);
