<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2024/10/19 18:03:03
sfConfig::add(array(
  'mod_informationobject_enabled' => true,
  'mod_informationobject_view_class' => 'sfPHP',
));
