<?php
// auto-generated by sfSecurityConfigHandler
// date: 2024/10/19 17:39:53
$this->security = array (
  'import' => 
  array (
    'credentials' => 'administrator',
  ),
  'importselect' => 
  array (
    'credentials' => 'administrator',
  ),
  'validatecsv' => 
  array (
    'credentials' => 'administrator',
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
